name: first_task

# image_shape: [3, 256, 256]
image_shape: [3, 96, 96]
dataset_path: data/BJ_juice1/zarr/BJ_juice1.zarr

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: ${task.image_shape}
      type: rgb
    # camera_1:
    #   shape: ${task.image_shape}
    #   type: rgb
    # camera_2:
    #   shape: ${task.image_shape}
    #   type: rgb
    # camera_3:
    #   shape: ${task.image_shape}
    #   type: rgb
    # camera_4:
    #   shape: ${task.image_shape}
    #   type: rgb
    agent_pos:
      shape: [7]
      type: low_dim
  action: 
    shape: [7]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.pusht_image_dataset_first_task.PushTImageDataset
  # shape_meta: *shape_meta
  zarr_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  # n_obs_steps: ${dataset_obs_steps}
  # n_latency_steps: ${n_latency_steps}
  # use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  # delta_action: False

